spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/debezium_mysql?useSSL=false&useInformationSchema=true&allowPublicKeyRetrieval=true
    username: sql-user
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
    port: 9999